/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static project.homepage1.DBPASS;
import static project.homepage1.DBURL;
import static project.homepage1.DBUSER;

/**
 *
 * @author Mahe
 */
public class ADD extends javax.swing.JFrame {
    public static final String DBURL = "jdbc:oracle:thin:@HPPRO540:1521:XE ";

    public static final String DBUSER = "system";

    public static final String DBPASS = "tushar22";
    /**
     * Creates new form ADD
     */
    public ADD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(null);

        jLabel1.setText("FName");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 130, 60, 14);

        jLabel2.setText("Guardian");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 220, 70, 14);

        jLabel3.setText("Student_ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 80, 14);

        jLabel4.setText("LName");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 160, 60, 14);

        jLabel5.setText("Pincode");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 190, 60, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(260, 100, 100, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(260, 130, 100, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(260, 160, 100, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(260, 190, 100, 20);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(260, 220, 100, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\DBS Project\\Project\\src\\project\\logo2.jpg")); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 90);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 290, 100, 23);

        jButton2.setText("REMOVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 290, 100, 23);

        jCheckBox1.setText("single");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(50, 250, 80, 23);

        jCheckBox2.setText("double");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(190, 250, 81, 23);

        jCheckBox3.setText("AC");
        jPanel1.add(jCheckBox3);
        jCheckBox3.setBounds(310, 250, 70, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{
        int i = Integer.parseInt(jTextField1.getText());
       String fn = jTextField2.getText();
       String ln = jTextField3.getText();
       int p = Integer.parseInt(jTextField4.getText());
       String g = jTextField5.getText();
       
        Class.forName("oracle.jdbc.driver.OracleDriver");  
               Connection con = DriverManager.getConnection(DBURL, DBUSER, DBPASS);
                
                 Statement statement = (Statement) con.createStatement();
                 Statement statement2 = (Statement) con.createStatement();


             
             statement.executeUpdate("insert into student(student_id,fname,lname,pincode,guardian,password) values("+i+",'"+fn+"','"+ln+"',"+p+",'"+g+"','abcd')");    
             if (jCheckBox1.isSelected() & jCheckBox3.isSelected()){
                statement2.executeUpdate("insert into room_occupy(room_no,occupant,occ_date) values((with t(room_no) as (select room_no from room where occupancy<1 and type=1 and ac=1) select room_no from t where rownum=1),"+i+",sysdate)");
             }
             else if (jCheckBox1.isSelected() & !jCheckBox3.isSelected()){
                 statement2.executeUpdate("insert into room_occupy(room_no,occupant,occ_date) values((with t(room_no) as (select room_no from room where occupancy<1 and type=1 and ac=0) select room_no from t where rownum=1),"+i+",sysdate)");
             }
             else if (jCheckBox2.isSelected() & jCheckBox3.isSelected()){
                 statement2.executeUpdate("insert into room_occupy(room_no,occupant,occ_date) values((with t(room_no) as (select room_no from room where occupancy<2 and type=2 and ac=1) select room_no from t where rownum=1),"+i+",sysdate)");
             }
             else if (jCheckBox2.isSelected() & !jCheckBox3.isSelected()){
                 statement2.executeUpdate("insert into room_occupy(room_no,occupant,occ_date) values((with t(room_no) as (select room_no from room where occupancy<2 and type=2 and ac=0) select room_no from t where rownum=1),"+i+",sysdate)");
             }
             statement.close();
             statement2.close();

        con.close();
     
  
       }
       catch(Exception e){

       }
       finally{
              update_student u=new update_student();
        u.setVisible(true);
        this.dispose();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int i = Integer.parseInt(jTextField1.getText());
       try{
        Class.forName("oracle.jdbc.driver.OracleDriver");  
               Connection con = DriverManager.getConnection(DBURL, DBUSER, DBPASS);
                
                 Statement statement = (Statement) con.createStatement();
                 statement.executeUpdate("delete from late_entry where student_id="+i);
                 statement.executeUpdate("delete from complaint where registered_by="+i);
                 statement.executeUpdate("delete from watchlist where student_id="+i);
                 statement.executeUpdate("delete from leave where student_id="+i);
                 statement.executeUpdate("update room set occupancy=occupancy-1 where room_no in(select room_no from room natural join room_occupy where occupant="+i+")");
             statement.executeUpdate("delete from room_occupy where occupant="+i);
             statement.executeUpdate("delete from student where student_id="+i);    

        statement.close();

        con.close();
         update_student u=new update_student();
        u.setVisible(true);
        this.dispose();
  
  
       }
       catch(Exception e){
           e.printStackTrace();
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
